import { z } from "zod";

export const ICON_KEYS = [
  "motor",
  "arrefecimento",
  "transmissao",
  "suspensao",
  "freios",
  "escapamento",
  "direcao",
  "lubrificacao",
  "diagnostico",
  "geral",
] as const;

export const iconKeySchema = z.enum(ICON_KEYS);
export type IconKey = z.infer<typeof iconKeySchema>;

export const serviceCardSchema = z.object({
  icon: iconKeySchema,
  title: z.string().min(1),
  description: z.string().min(1),
  bullets: z.array(z.string().min(1)).min(1),
  ctaLabel: z.string().min(1),
});
export type ServiceCard = z.infer<typeof serviceCardSchema>;

export const catalogCategorySchema = z.object({
  id: z.string().min(1),
  icon: iconKeySchema,
  name: z.string().min(1),
  items: z.array(z.string().min(1)).min(1),
});
export type CatalogCategory = z.infer<typeof catalogCategorySchema>;

export const siteContentSchema = z.object({
  siteTitle: z.string().min(1),
  whatsappNumber: z.string().min(1),
  phoneDisplay: z.string().min(1),
  logoUrl: z.string().min(1),
  heroVideoUrl: z.string().min(1),
  hero: z.object({
    badge: z.string().min(1),
    titleMain: z.string().min(1),
    titleHighlight: z.string().min(1),
    subtitle: z.string().min(1),
  }),
  trustBullets: z.array(z.string().min(1)).min(1),
  services: z.array(serviceCardSchema).min(1),
  catalog: z.array(catalogCategorySchema).min(1),
  location: z.object({
    addressLine1: z.string().min(1),
    addressLine2: z.string().min(1),
    hoursWeekday: z.string().min(1),
    hoursSaturday: z.string().min(1),
  }),
  cta: z.object({
    title: z.string().min(1),
  }),
});
export type SiteContent = z.infer<typeof siteContentSchema>;

export const DEFAULT_CONTENT: SiteContent = {
  siteTitle: "BW Mecânica — Suspensão, Freios e Motor em Terra Roxa - PR",
  whatsappNumber: "5544998029654",
  phoneDisplay: "(44) 99802-9654",
  logoUrl: "/logo.png",
  heroVideoUrl: "/hero-video.mp4",
  hero: {
    badge: "Terra Roxa · PR",
    titleMain: "Diagnóstico certeiro.",
    titleHighlight: "Sem enrolação.",
    subtitle:
      "Suspensão, freios e motor com transparência do início ao fim. Você vê o problema, entende a solução e só paga pelo que precisa.",
  },
  trustBullets: [
    "Diagnóstico mostrado ao cliente",
    "Só trocamos o que precisa",
    "Atendimento direto por WhatsApp",
  ],
  services: [
    {
      icon: "suspensao",
      title: "Barulhos ou trepidação na suspensão?",
      description:
        "Recuperamos o conforto e a estabilidade do seu carro com revisão completa de amortecedores, molas, buchas e alinhamento.",
      bullets: ["Amortecedores e molas", "Buchas e pivôs", "Alinhamento e geometria"],
      ctaLabel: "Falar sobre suspensão",
    },
    {
      icon: "freios",
      title: "Chiado ou demora pra parar?",
      description:
        "Revisão completa do sistema de freios para você parar com segurança em qualquer situação.",
      bullets: ["Pastilhas e discos", "Fluido de freio", "Revisão do sistema completo"],
      ctaLabel: "Falar sobre freios",
    },
    {
      icon: "motor",
      title: "Motor perdendo força ou consumindo mais?",
      description:
        "Diagnóstico e reparo para manter o motor com performance e economia, sem trocar peça que ainda serve.",
      bullets: ["Diagnóstico de falhas", "Revisão programada", "Reparo do motor"],
      ctaLabel: "Falar sobre motor",
    },
  ],
  catalog: [
    {
      id: "motor",
      icon: "motor",
      name: "Motor",
      items: [
        "Troca de óleo do motor",
        "Troca do filtro de óleo",
        "Troca do filtro de ar",
        "Troca do filtro de combustível",
        "Troca do filtro de cabine",
        "Troca de velas (parte mecânica)",
        "Troca de correia dentada",
        "Troca da correia de acessórios",
        "Troca do tensor e rolamentos",
        "Troca da bomba d'água",
        "Regulagem do motor",
        "Limpeza do sistema de admissão",
        "Limpeza do corpo de borboleta (parte mecânica)",
        "Limpeza de bicos injetores",
        "Troca de juntas",
        "Troca da tampa de válvulas",
        "Troca do cárter",
        "Troca de retentores",
        "Troca de pistões",
        "Troca de anéis",
        "Troca de bronzinas",
        "Troca de bielas",
        "Troca do virabrequim",
        "Troca do comando de válvulas",
        "Troca de tuchos",
        "Troca de válvulas",
        "Retífica de cabeçote",
        "Retífica do motor",
        "Recondicionamento do motor",
        "Motor completo",
      ],
    },
    {
      id: "arrefecimento",
      icon: "arrefecimento",
      name: "Sistema de arrefecimento",
      items: [
        "Troca do líquido de arrefecimento",
        "Limpeza do sistema de arrefecimento",
        "Flush do radiador",
        "Troca do radiador",
        "Troca da bomba d'água",
        "Troca da válvula termostática",
        "Troca de mangueiras",
        "Troca do reservatório de expansão",
        "Troca da tampa do reservatório",
        "Reparo de vazamentos",
      ],
    },
    {
      id: "transmissao",
      icon: "transmissao",
      name: "Transmissão",
      items: [
        "Troca de óleo da transmissão manual",
        "Troca de óleo do câmbio automático",
        "Flush do câmbio automático",
        "Troca da embreagem",
        "Troca do kit de embreagem",
        "Troca do volante do motor",
        "Troca do cabo da embreagem",
        "Troca do atuador hidráulico",
        "Troca do diferencial",
        "Troca de semieixos",
        "Troca de juntas homocinéticas",
        "Troca de coifas",
        "Reparo do câmbio",
        "Revisão do câmbio",
      ],
    },
    {
      id: "suspensao",
      icon: "suspensao",
      name: "Suspensão",
      items: [
        "Troca de amortecedores",
        "Troca de molas",
        "Troca de batentes",
        "Troca de coxins",
        "Troca de bandejas",
        "Troca de buchas",
        "Troca de pivôs",
        "Troca de bieletas",
        "Troca da barra estabilizadora",
        "Troca da caixa de direção",
        "Troca de terminais de direção",
        "Troca de barras axiais",
        "Alinhamento",
        "Balanceamento",
        "Cambagem (quando aplicável)",
      ],
    },
    {
      id: "freios",
      icon: "freios",
      name: "Freios",
      items: [
        "Troca de pastilhas",
        "Troca de discos",
        "Troca de lonas",
        "Troca de tambores",
        "Troca de cilindros de roda",
        "Troca do cilindro mestre",
        "Troca de pinças",
        "Troca de flexíveis",
        "Troca de tubulações",
        "Troca do fluido de freio",
        "Sangria do sistema",
        "Regulagem do freio de mão",
      ],
    },
    {
      id: "escapamento",
      icon: "escapamento",
      name: "Escapamento",
      items: [
        "Troca do escapamento",
        "Troca do silencioso",
        "Troca do intermediário",
        "Troca do catalisador",
        "Troca de suportes",
        "Solda no escapamento",
        "Reparo de vazamentos",
      ],
    },
    {
      id: "direcao",
      icon: "direcao",
      name: "Direção",
      items: [
        "Troca da caixa de direção",
        "Troca da bomba hidráulica",
        "Troca de mangueiras hidráulicas",
        "Troca do fluido da direção hidráulica",
        "Revisão da direção",
        "Reparo de vazamentos",
      ],
    },
    {
      id: "lubrificacao",
      icon: "lubrificacao",
      name: "Lubrificação",
      items: [
        "Troca de óleo do motor",
        "Troca de óleo da transmissão",
        "Troca de óleo do diferencial",
        "Lubrificação de componentes",
        "Engraxamento",
      ],
    },
    {
      id: "diagnostico",
      icon: "diagnostico",
      name: "Diagnóstico mecânico",
      items: [
        "Inspeção veicular",
        "Revisão preventiva",
        "Revisão periódica",
        "Diagnóstico de ruídos",
        "Diagnóstico de vibrações",
        "Diagnóstico de vazamentos",
        "Diagnóstico de superaquecimento",
        "Avaliação pré-compra",
      ],
    },
    {
      id: "geral",
      icon: "geral",
      name: "Serviços gerais",
      items: [
        "Revisão completa",
        "Check-up automotivo",
        "Aperto geral",
        "Substituição de parafusos e fixadores",
        "Limpeza de componentes mecânicos",
        "Higienização do cofre do motor",
        "Preparação para inspeção veicular",
        "Instalação de protetor de cárter",
        "Troca de suportes e coxins do motor",
        "Troca de coxins do câmbio",
      ],
    },
  ],
  location: {
    addressLine1: "Estrada para Palotina, km 1",
    addressLine2: "Terra Roxa – PR, 85990-000",
    hoursWeekday: "Segunda a sexta: 8h às 18h",
    hoursSaturday: "Sábado: 8h30 às 12h",
  },
  cta: {
    title: "Marque agora e resolva o problema do seu carro",
  },
};
